"use client";

import { useEffect, useState } from "react";
import { Download, FileText, X } from "lucide-react";
import jsPDF from "jspdf";
import { showToast } from "./ToastHost";
import { addNotification } from "./appEvents";

type Incident = {
  id: number;
  type: string;
  location: string;
  severity: string;
  population: number;
  casualties: number;
};

export default function ExportReport({ incidents }: { incidents: Incident[] }) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    function openExport() {
      setOpen(true);
    }

    window.addEventListener("dashboard-export", openExport);

    return () => {
      window.removeEventListener("dashboard-export", openExport);
    };
  }, []);

  function exportReport() {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("DisasterIQ", 20, 20);

    doc.setFontSize(14);
    doc.text("Emergency Operations Report", 20, 32);

    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 45);
    doc.text(`Active Incidents: ${incidents.length}`, 20, 53);
    doc.text("System Status: Operational", 20, 61);
    doc.text("Database: Supabase Connected", 20, 69);
    doc.text("Priority Engine: Enabled", 20, 77);

    doc.setFontSize(13);
    doc.text("Incident Summary", 20, 95);

    doc.setFontSize(9);

    incidents.slice(0, 8).forEach((incident, index) => {
      const y = 108 + index * 10;
      doc.text(
        `${index + 1}. ${incident.type} | ${incident.location} | ${incident.severity} | Population: ${incident.population} | Casualties: ${incident.casualties}`,
        20,
        y,
        { maxWidth: 170 }
      );
    });

    doc.setFontSize(13);
    doc.text("Operational Modules", 20, 205);

    doc.setFontSize(9);
    doc.text(
      "DisasterIQ includes incident reporting, priority scoring, resource allocation, volunteer deployment, relief center assignment, route optimization, real-time Supabase sync, analytics, PDF export, and command-center decision support.",
      20,
      217,
      { maxWidth: 170 }
    );

    doc.setFontSize(8);
    doc.text("Generated by DisasterIQ Emergency Resource Allocation System", 20, 285);

    doc.save("DisasterIQ_Professional_Report.pdf");

    addNotification(
      "PDF report exported",
      `Professional report generated for ${incidents.length} active incidents.`,
      "export"
    );

    showToast("Professional PDF report exported");
    setOpen(false);
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="fixed bottom-6 right-6 z-[70] flex items-center gap-2 rounded-full border border-white/20 bg-black border-white/20 text-white text-black px-5 py-3 text-xs font-semibold shadow-xl transition hover:-translate-y-0.5 hover:bg-white hover:text-black"
      >
        <Download className="h-4 w-4" />
        Export
      </button>

      {open && (
        <div className="fixed inset-0 z-[999999] flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0f172a] p-5 shadow-2xl">
            <div className="mb-4 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-slate-300" />
                <div>
                  <h2 className="text-sm font-semibold">Export PDF Report</h2>
                  <p className="text-xs text-slate-500">
                    Generate a professional DisasterIQ operations report.
                  </p>
                </div>
              </div>

              <button
                onClick={() => setOpen(false)}
                className="rounded-md border border-white/10 p-1 text-slate-400 transition hover:bg-white/10 hover:text-white"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="space-y-2 rounded-xl border border-white/10 bg-black/30 p-4 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-500">Active incidents</span>
                <span>{incidents.length}</span>
              </div>

              <div className="flex justify-between">
                <span className="text-slate-500">Database</span>
                <span className="text-green-300">Supabase connected</span>
              </div>

              <div className="flex justify-between">
                <span className="text-slate-500">Priority engine</span>
                <span className="text-slate-300">Enabled</span>
              </div>

              <div className="flex justify-between">
                <span className="text-slate-500">Report type</span>
                <span>PDF</span>
              </div>
            </div>

            <div className="mt-5 flex justify-end gap-2">
              <button
                onClick={() => setOpen(false)}
                className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-300 transition hover:bg-white/10"
              >
                Cancel
              </button>

              <button
                onClick={exportReport}
                className="rounded-lg border border-white/20 bg-white px-3 py-2 text-xs font-semibold text-black transition hover:bg-slate-200"
              >
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}