import { Download } from "lucide-react";
import { showToast } from "./ToastHost";

type Props = {
  incidents: number;
};

export default function ExportReport({ incidents }: Props) {
  function exportReport() {
    const report = `
DisasterIQ Emergency Operations Report

Active Incidents: ${incidents}
System Status: Operational
Database: Supabase Connected
Priority Engine: Enabled

Generated by DisasterIQ.
`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "DisasterIQ_Report.txt";
    link.click();

    URL.revokeObjectURL(url);
    showToast("Emergency report exported");
  }

  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
      <div className="mb-3 flex items-center gap-2">
        <Download className="h-4 w-4 text-blue-300" />
        <h2 className="text-sm font-semibold">Export Report</h2>
      </div>

      <p className="mb-4 text-xs text-slate-500">
        Download a quick emergency operations summary.
      </p>

      <button
        onClick={exportReport}
        className="rounded-lg border border-blue-500/20 bg-blue-500/10 px-3 py-2 text-xs text-blue-300 hover:bg-blue-500/20"
      >
        Download Report
      </button>
    </div>
  );
}