"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Bell, X } from "lucide-react";
import type { AppNotification } from "./appEvents";

export default function NotificationDrawer() {
  const [open, setOpen] = useState(false);
  const [read, setRead] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [notifications, setNotifications] = useState<AppNotification[]>([]);

  function loadNotifications() {
    const saved = localStorage.getItem("disasteriq-live-notifications");
    setNotifications(saved ? JSON.parse(saved) : []);
  }

  useEffect(() => {
    setMounted(true);
    loadNotifications();

    window.addEventListener("disasteriq-notification", loadNotifications);

    return () => {
      window.removeEventListener("disasteriq-notification", loadNotifications);
    };
  }, []);

  function dotColor(type: string) {
    if (type === "critical") return "bg-red-400";
    if (type === "resource") return "bg-emerald-400";
    if (type === "broadcast") return "bg-yellow-400";
    if (type === "mission") return "bg-violet-400";
    if (type === "export") return "bg-blue-400";
    return "bg-slate-400";
  }

  const drawer =
    open && mounted
      ? createPortal(
          <div className="fixed inset-0 z-[999999] flex justify-end bg-black/70 backdrop-blur-sm">
            <div className="h-screen w-[390px] overflow-y-auto border-l border-white/10 bg-[#0f172a] p-5 shadow-2xl">
              <div className="mb-5 flex items-center justify-between">
                <div>
                  <h2 className="text-sm font-semibold text-white">
                    Notification Center
                  </h2>
                  <p className="text-xs text-slate-500">
                    Live operational alerts generated by dashboard actions.
                  </p>
                </div>

                <button
                  onClick={() => setOpen(false)}
                  className="rounded-md border border-white/10 p-1 text-slate-400 transition hover:bg-white/10 hover:text-white"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>

              {notifications.length === 0 ? (
                <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-xs text-slate-500">
                  No live notifications yet. Generate a plan, broadcast, export,
                  or use Mission Control.
                </div>
              ) : (
                <div className="space-y-2">
                  {notifications.map((item) => (
                    <div
                      key={item.id}
                      className="w-full rounded-lg border border-white/10 bg-black/30 p-3 text-xs transition hover:border-white/30 hover:bg-white/[0.05]"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex min-w-0 flex-1 gap-2">
                          <span
                            className={`mt-1 h-2 w-2 shrink-0 rounded-full ${dotColor(
                              item.type
                            )}`}
                          />

                          <div className="min-w-0">
                            <p className="break-words font-medium text-slate-200">
                              {item.title}
                            </p>
                            <p className="mt-1 break-words text-[11px] leading-4 text-slate-500">
                              {item.detail}
                            </p>
                          </div>
                        </div>

                        <span className="shrink-0 text-[11px] text-slate-500">
                          {item.time}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>,
          document.body
        )
      : null;

  return (
    <>
      <button
        onClick={() => {
          setOpen(true);
          setRead(true);
          loadNotifications();
        }}
        className="relative rounded-full border border-white/10 bg-white/[0.03] px-3 py-1 text-[11px] text-slate-300 transition hover:border-white/30 hover:bg-white/[0.08]"
      >
        <Bell className="mr-1 inline h-3 w-3" />
        Alerts

        {!read && notifications.length > 0 && (
          <span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-red-400" />
        )}
      </button>

      {drawer}
    </>
  );
}